<a href="https://colab.research.google.com/github/ptobarra/20210515_deeplearning.io/blob/main/20210515_convolution2d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
import numpy as np
from scipy.signal import convolve2d

In [85]:
input1 = np.array([[10, 0, 0, 0, 0, 0],
                  [10, 10, 0, 0, 0, 0],
                  [10, 10, 10, 0, 0, 0],
                  [10, 10, 10, 10, 0, 0],
                  [10, 10, 10, 10, 10, 0],
                  [10, 10, 10, 10, 10, 10]])

In [86]:
kernel = np.array([[0, 1, 1, 0],
                   [1, 3, -3, -1],
                   [1, 3, -3, -1],
                   [0, 1, -1, 0]])

In [87]:
input1

array([[10,  0,  0,  0,  0,  0],
       [10, 10,  0,  0,  0,  0],
       [10, 10, 10,  0,  0,  0],
       [10, 10, 10, 10,  0,  0],
       [10, 10, 10, 10, 10,  0],
       [10, 10, 10, 10, 10, 10]])

In [88]:
kernel

array([[ 0,  1,  1,  0],
       [ 1,  3, -3, -1],
       [ 1,  3, -3, -1],
       [ 0,  1, -1,  0]])

In [89]:
output1 = convolve2d(in1=input1, in2=kernel, mode='valid')

In [90]:
# detecta bien 45º en una diagonal
output1

array([[-30, -30,   0],
       [  0, -30, -30],
       [ 20,   0, -30]])

In [91]:
input2 = np.array([[10, 10, 10, 10, 10, 10],
                  [10, 10, 10, 10, 10, 10],
                  [10, 10, 10, 10, 10, 10],
                  [10, 10, 10, 10, 10, 10],
                  [10, 10, 10, 10, 10, 10],
                  [10, 10, 10, 10, 10, 10]])

In [92]:
output2 = convolve2d(in1=input2, in2=kernel, mode='valid')

In [93]:
#aqui no filtra nada
output2

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [94]:
input3 = np.transpose(input1)

In [95]:
input3

array([[10, 10, 10, 10, 10, 10],
       [ 0, 10, 10, 10, 10, 10],
       [ 0,  0, 10, 10, 10, 10],
       [ 0,  0,  0, 10, 10, 10],
       [ 0,  0,  0,  0, 10, 10],
       [ 0,  0,  0,  0,  0, 10]])

In [96]:
output3 = convolve2d(in1=input3, in2=kernel, mode='valid')

In [97]:
# detecta bien el cambio de 45º en la otra diagonal
output3

array([[50, 20, 20],
       [50, 50, 20],
       [20, 50, 50]])

In [98]:
input4 = np.array([[10, 10, 10, 0, 0, 0],
                  [10, 10, 10, 0, 0, 0],
                  [10, 10, 10, 0, 0, 0],
                  [10, 10, 10, 0, 0, 0],
                  [10, 10, 10, 0, 0, 0],
                  [10, 10, 10, 0, 0, 0]])

In [99]:
output4 = convolve2d(in1=input4, in2=kernel, mode='valid')

In [100]:
# no detecta bien bordes verticales y por ende tampoco horizontales
output4

array([[  0, -80, -20],
       [  0, -80, -20],
       [  0, -80, -20]])

In [101]:
input5 = np.array([[0, 0, 0, 0, 0, 0],
                  [0, 10, 10, 10, 10, 0],
                  [0, 10, 20, 20, 10, 0],
                  [0, 10, 20, 20, 10, 0],
                  [0, 10, 10, 10, 10, 0],
                  [0, 0, 0, 0, 0, 0]])

In [102]:
output5 = convolve2d(in1=input5, in2=kernel, mode='valid')

In [103]:
# es un detector de contraste
output5

array([[ 90,  40, -30],
       [120,  20, -80],
       [ 70,   0, -70]])